name: CI

on:
  push:
    branches: [main]
    tags: ["v[0-9]*", "[0-9]+.[0-9]+*"]
  pull_request:

jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v4
        with: { python-version: "3.9" }

      - name: Analisis Estatico del Codigo
        run: |
          pip install pre-commit
          pre-commit install
          pre-commit run --all-files --show-diff-on-failure

      - name: Pruebas Unitarias
        run: python -m unittest discover
